# Generated by Django 5.2.8 on 2025-11-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Documento'),
        ),
    ]
