# Generated by Django 5.2.8 on 2025-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_movimiento_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='stock_actual',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo_producto',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Código de Producto'),
            preserve_default=False,
        ),
    ]
